name: cleanup
on: push
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Start test database
        run: echo "DB Started"
      - name: Flaky check
        run: echo "${{vars.DEPLOY_RGION}"
      - name: Stop test database
        if: always()
        run: echo "Always runs"

