name: deets
on: push
jobs:
  deets:
    runs-on: ubuntu-latest
    steps:
      - name: deets
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.ref_name  }}"
          echo "${{ github.sha  }}"
          echo "${{ github.event_name  }}"
          echo "${{ runner.os }}"
