name: handoff
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: file creation
        run: echo "hello world" > app.txt
      - uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: app.txt
  verify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-package
      - name: test the file
        run: test -f app.txt
