name: secret-puller
on: push
jobs:
  secret-puller:
    runs-on: ubuntu-latest
    steps:
      - name: secret-pull
        env: 
          APP_TOKEN: ${{secrets.APP_TOKEN}}
        run: |
          if [-n "$APP_TOKEN"]; then
            echo "token is available to this step"
          fi
